### ISSUE TITLE
Getting Error from speeder container

### ISSUE THREAD

**Issue by gonzalu** [dbrennand/speeder#11]
Hello, 

i get the following error as soon as I start the docker stack 

```
speeder   | 2023-10-18 02:00:59.492 | DEBUG    | __main__:<module>:91 - Speedtest for server ID: 78 succeeded.
speeder   | Traceback (most recent call last):
speeder   |   File "//speeder.py", line 104, in <module>
speeder   |     "server_name": json_result[0]["server"]["name"],
speeder   | TypeError: 'NoneType' object is not subscriptable
speeder exited with code 1
```

**Comment by dbrennand** [comment]
Hi @gonzalu 

Thanks for reporting this. I will try and reproduce this error on my side.

**Comment by gonzalu** [comment]
Thank you. It may have been related to my container host being behind a proxy. After installing  the root certificates on the docker container, most errors have disappeared. I will continue to look for this error to see if it was related or unrelated to certificate errors.

**Comment by dbrennand** [comment]
Hi @gonzalu 

I'm not able to reproduce this issue on my side:

```
speeder  | 2023-11-05 13:21:41.997 | DEBUG    | __main__:<module>:91 - Speedtest for server ID: 78 succeeded.
speeder  | 2023-11-05 13:21:42.002 | DEBUG    | __main__:<module>:125 - Writing record to InfluxDB bucket: speeder for speedtest at 2023-11-05T13:21:41.977183122Z using server ID: 78.
speeder  | 2023-11-05 13:21:42.006 | DEBUG    | __main__:<module>:128 - Record:
speeder  | [{'measurement': 'speeder', 'tags': {'server_name': 'Virginia, United States, OVH', 'server_url': 'https://speed.riverside.rocks/', 'ip': '', 'hostname': '', 'region': '', 'city': '', 'country': '', 'org': '', 'timezone': ''}, 'time': '2023-11-05T13:21:41.977183122Z', 'fields': {'bytes_sent': 102760448, 'bytes_received': 912753747, 'ping': 15.0, 'jitter': 3.4, 'upload': 52.68, 'download': 467.95}}]
```

**Comment by gonzalu** [comment]
Thank you, Daniel. Our proxy seems to have been the culprit. Once I installed the right certs on the container, it is working well.

**Comment by dbrennand** [comment]
Great! Glad to hear it! 🙂

**Comment by jarjumarvin** [comment]
Hey there! Having the same issue.

```
2024-08-25 12:52:02.302 | DEBUG    | __main__:<module>:34 - Starting speeder version: 1.1.0.
2024-08-25 12:52:02.303 | DEBUG    | __main__:<module>:60 - Connecting to InfluxDB: influxdb:8086 with organisation: speeder.
2024-08-25 12:52:02.310 | DEBUG    | __main__:<module>:71 - Running speedtest for server ID: 28.
2024-08-25 12:52:02.452 | DEBUG    | __main__:<module>:91 - Speedtest for server ID: 28 succeeded.
Traceback (most recent call last):
  File "//speeder.py", line 104, in <module>
    "server_name": json_result[0]["server"]["name"],
TypeError: 'NoneType' object is not subscriptable
```

My setup is a bit more complicated. Running my speeder / grafana / etc. stack through Portainer on an alpine LXC inside a Proxmox host. Any ideas about how I could go about debugging this?

**Comment by dbrennand** [comment]
Hi @jarjumarvin 

I made some changes in https://github.com/dbrennand/speeder/tree/1.2.0 - Are you able to build the container on this branch and see if the `json_result` is empty?
